// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4Z6kQLbbqB1Det-zFCo5OdYlzgWl9C7k',
    appId: '1:203928614103:web:6d6056fd3a6568975fac92',
    messagingSenderId: '203928614103',
    projectId: 'chat-me-50970',
    authDomain: 'chat-me-50970.firebaseapp.com',
    storageBucket: 'chat-me-50970.appspot.com',
    measurementId: 'G-QW09D81188',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIK0qSIToiZWGMbMvbCS3UYY9VdJgBEdM',
    appId: '1:203928614103:android:20d503f243dc84185fac92',
    messagingSenderId: '203928614103',
    projectId: 'chat-me-50970',
    storageBucket: 'chat-me-50970.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf5thNHpCqcRUa7ovEZbcYXdVoKx2yMO0',
    appId: '1:203928614103:ios:2d77972ac313126e5fac92',
    messagingSenderId: '203928614103',
    projectId: 'chat-me-50970',
    storageBucket: 'chat-me-50970.appspot.com',
    iosBundleId: 'com.chatMe.chatMeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf5thNHpCqcRUa7ovEZbcYXdVoKx2yMO0',
    appId: '1:203928614103:ios:ca82474e68e1333a5fac92',
    messagingSenderId: '203928614103',
    projectId: 'chat-me-50970',
    storageBucket: 'chat-me-50970.appspot.com',
    iosBundleId: 'com.chatMe.chatMeApp.RunnerTests',
  );
}
