// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:chat_me_app/dtos/DTOUser.dart' as prefix1;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;

// ignore_for_file: camel_case_types
// ignore_for_file: implementation_imports
// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'DTOUser',
            r'.DTOUser',
            134217735,
            0,
            const prefix0.JsonSerializable(),
            const <int>[0, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            const <int>[
              16,
              17,
              18,
              19,
              20,
              1,
              2,
              3,
              4,
              5,
              6,
              7,
              8,
              9,
              10,
              11,
              12,
              13,
              14
            ],
            const <int>[],
            -1,
            {},
            {},
            {r'': (bool b) => () => b ? prefix1.DTOUser() : null},
            -1,
            0,
            const <int>[],
            const <Object>[const prefix0.JsonSerializable()],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'privateChatRooms',
            84017157,
            0,
            const prefix0.JsonSerializable(),
            -1,
            1,
            2,
            const <int>[3],
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 1),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 2),
        r.MethodMirrorImpl(r'username', 2097155, 0, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'username=', 1310724, 0, -1, -1, -1, const <int>[],
            const <int>[1], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'firstname', 2097155, 0, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'friends', 35651587, 0, -1, 5, 6, const <int>[0],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'friends=', 1310724, 0, -1, -1, -1, const <int>[],
            const <int>[2], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'creationDate', 2097155, 0, -1, 7, 7, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'creationDate=',
            1310724,
            0,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[3],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'email', 2097155, 0, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'email=', 1310724, 0, -1, -1, -1, const <int>[],
            const <int>[4], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'lastname', 2097155, 0, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'lastname=', 1310724, 0, -1, -1, -1, const <int>[],
            const <int>[5], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'firstname=', 1310724, 0, -1, -1, -1, const <int>[],
            const <int>[6], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'', 64, 0, -1, 0, 0, const <int>[], const <int>[],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 2097154, -1, -1, 8, 8, const <int>[],
            const <int>[7], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 2097154, -1, -1, 9, 9, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            524290,
            -1,
            -1,
            -1,
            -1,
            const <int>[],
            const <int>[8],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 2097155, -1, -1, 10, 10, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            2097155,
            -1,
            -1,
            11,
            11,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(
            r'_privateChatRooms',
            84017254,
            2,
            const prefix0.JsonSerializable(),
            -1,
            1,
            2,
            const <int>[3],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            67239942,
            4,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            151126022,
            7,
            const prefix0.JsonSerializable(),
            -1,
            5,
            6,
            const <int>[0],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            67239942,
            9,
            const prefix0.JsonSerializable(),
            -1,
            7,
            7,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            67239942,
            11,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            67239942,
            13,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'value',
            67239942,
            14,
            const prefix0.JsonSerializable(),
            -1,
            4,
            4,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            134348806,
            16,
            const prefix0.JsonSerializable(),
            -1,
            12,
            12,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            134348806,
            18,
            const prefix0.JsonSerializable(),
            -1,
            13,
            13,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.DTOUser,
        const m.TypeValue<List<prefix1.DTOPrivateChatRoom>>().type,
        List,
        prefix1.DTOPrivateChatRoom,
        String,
        const m.TypeValue<List<prefix1.DTOUser>>().type,
        List,
        DateTime,
        bool,
        String,
        int,
        Type,
        Object,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'privateChatRooms': (dynamic instance) => instance.privateChatRooms,
        r'username': (dynamic instance) => instance.username,
        r'firstname': (dynamic instance) => instance.firstname,
        r'friends': (dynamic instance) => instance.friends,
        r'creationDate': (dynamic instance) => instance.creationDate,
        r'email': (dynamic instance) => instance.email,
        r'lastname': (dynamic instance) => instance.lastname
      },
      {
        r'privateChatRooms=': (dynamic instance, value) =>
            instance.privateChatRooms = value,
        r'username=': (dynamic instance, value) => instance.username = value,
        r'friends=': (dynamic instance, value) => instance.friends = value,
        r'creationDate=': (dynamic instance, value) =>
            instance.creationDate = value,
        r'email=': (dynamic instance, value) => instance.email = value,
        r'lastname=': (dynamic instance, value) => instance.lastname = value,
        r'firstname=': (dynamic instance, value) => instance.firstname = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
